### ISSUE TITLE
possible to mass-convert images

### ISSUE THREAD

**Issue by Vortetty** [codebox/mosaic#10]
Is there a way to mass convert images using this? trying https://github.com/dvdtho/python-photo-mosaic but it is looking at around ~~1.72374429224 years~~ (incorrect math) 6.291666 days per image and i have over 900 images.  i mostly need a way to run this and have it replace the file it has converted.

**Comment by codebox** [comment]
> Is there a way to mass convert images using this?

That isn't supported directly, but you could write a shell script to call this utility once for each image in your batch

> but it is looking at around 6.291666 days per image and i have over 900 images.

You can adjust [this parameter](https://github.com/codebox/mosaic/blob/master/mosaic.py#L8) to reduce processing time

> i mostly need a way to run this and have it replace the file it has converted.

This is easy to achieve, particularly if you are using a shell script as described above, one the mosaic image is complete just rename it so that it overwrites the original image

**Comment by Vortetty** [comment]
@codebox ok! how does the script actually start itself once called? i have a script in python that calls a fork of this but if i can modify the script to run this, that will be easier than dos/bash scripting.

**Comment by Vortetty** [comment]
never mind, i figured it out. definitely nice to have it use all but one core.
